language: python
python:
    - "3.8"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/espModbus/espModbus.ino PLATFORMIO_CI_EXTRA_ARGS="--board=lolin32"
    - CPPLINT=true

install:
    - pip install -U platformio
    - platformio lib -g install 1826
    - pip install -U cpplint

script:
    - if [[ "$CPPLINT" ]]; then cpplint --repository=. --recursive --linelength=200 --filter=-build/include  ./src; else platformio ci --lib="." $PLATFORMIO_CI_EXTRA_ARGS; fi

notifications:
    email:
        on_success: change
        on_failure: change
